name: Release the Authsignal ruby package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Build gem
        run: gem build authsignal-ruby.gemspec

      - name: Publish to RubyGems
        if: contains(github.ref, 'refs/tags/')
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push authsignal-ruby-*.gem
